version: '3'
services:
  client:
    build: ./client
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    restart: always
  server:
    build: ./server
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    restart: always
