version: '3'
services:
  nginx:
    image: nginx:1.17.0-alpine
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always
  server:
    build: ./server
    restart: always
